/**
 * This class is generated by jOOQ
 */
package tech.codingclub;

/**
 * This class is generated by jOOQ.
 *
 * A class modelling foreign key relationships between tables of the <code>public</code> 
 * schema
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.Identity<tech.codingclub.tables.records.MemberRecord, java.lang.Long> IDENTITY_MEMBER = Identities0.IDENTITY_MEMBER;
	public static final org.jooq.Identity<tech.codingclub.tables.records.TweetRecord, java.lang.Long> IDENTITY_TWEET = Identities0.IDENTITY_TWEET;

	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.UniqueKey<tech.codingclub.tables.records.FollowerRecord> FOLLOWER_USER_ID_FOLLOWING_ID_KEY = UniqueKeys0.FOLLOWER_USER_ID_FOLLOWING_ID_KEY;
	public static final org.jooq.UniqueKey<tech.codingclub.tables.records.MemberRecord> EMAIL_UNIQUE = UniqueKeys0.EMAIL_UNIQUE;
	public static final org.jooq.UniqueKey<tech.codingclub.tables.records.MemberRecord> MEMBER_PKEY = UniqueKeys0.MEMBER_PKEY;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.ForeignKey<tech.codingclub.tables.records.FollowerRecord, tech.codingclub.tables.records.MemberRecord> FOLLOWER__FOLLOWER_USER_ID_FKEY = ForeignKeys0.FOLLOWER__FOLLOWER_USER_ID_FKEY;
	public static final org.jooq.ForeignKey<tech.codingclub.tables.records.FollowerRecord, tech.codingclub.tables.records.MemberRecord> FOLLOWER__FOLLOWER_FOLLOWING_ID_FKEY = ForeignKeys0.FOLLOWER__FOLLOWER_FOLLOWING_ID_FKEY;

	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class Identities0 extends org.jooq.impl.AbstractKeys {
		public static org.jooq.Identity<tech.codingclub.tables.records.MemberRecord, java.lang.Long> IDENTITY_MEMBER = createIdentity(tech.codingclub.tables.Member.MEMBER, tech.codingclub.tables.Member.MEMBER.ID);
		public static org.jooq.Identity<tech.codingclub.tables.records.TweetRecord, java.lang.Long> IDENTITY_TWEET = createIdentity(tech.codingclub.tables.Tweet.TWEET, tech.codingclub.tables.Tweet.TWEET.ID);
	}

	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<tech.codingclub.tables.records.FollowerRecord> FOLLOWER_USER_ID_FOLLOWING_ID_KEY = createUniqueKey(tech.codingclub.tables.Follower.FOLLOWER, tech.codingclub.tables.Follower.FOLLOWER.USER_ID, tech.codingclub.tables.Follower.FOLLOWER.FOLLOWING_ID);
		public static final org.jooq.UniqueKey<tech.codingclub.tables.records.MemberRecord> EMAIL_UNIQUE = createUniqueKey(tech.codingclub.tables.Member.MEMBER, tech.codingclub.tables.Member.MEMBER.EMAIL);
		public static final org.jooq.UniqueKey<tech.codingclub.tables.records.MemberRecord> MEMBER_PKEY = createUniqueKey(tech.codingclub.tables.Member.MEMBER, tech.codingclub.tables.Member.MEMBER.ID);
	}

	private static class ForeignKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.ForeignKey<tech.codingclub.tables.records.FollowerRecord, tech.codingclub.tables.records.MemberRecord> FOLLOWER__FOLLOWER_USER_ID_FKEY = createForeignKey(tech.codingclub.Keys.MEMBER_PKEY, tech.codingclub.tables.Follower.FOLLOWER, tech.codingclub.tables.Follower.FOLLOWER.USER_ID);
		public static final org.jooq.ForeignKey<tech.codingclub.tables.records.FollowerRecord, tech.codingclub.tables.records.MemberRecord> FOLLOWER__FOLLOWER_FOLLOWING_ID_FKEY = createForeignKey(tech.codingclub.Keys.MEMBER_PKEY, tech.codingclub.tables.Follower.FOLLOWER, tech.codingclub.tables.Follower.FOLLOWER.FOLLOWING_ID);
	}
}
