package tech.codingclub.utility;

import java.io.*;
import java.util.ArrayList;
import java.util.Date;
import java.util.Scanner;

public class FileUtility {
    public static boolean createFile(String fileNameWithPath) {
        File file = new File(fileNameWithPath);
        boolean fileCreated = false;
        try {
            fileCreated = file.createNewFile();

        } catch (IOException e) {
            e.printStackTrace();
        }
        return fileCreated;
    }

    public static void main(String[] args) throws Exception {
        System.out.println("This Side is Suraj Patwa");
        System.out.println("Running FileUtility at " + new Date().toString());
        String nameOfNewFile = "D:\\TechCoding_1\\data\\Practice\\file" + "create-file.txt";
        boolean created = createFile(nameOfNewFile);
        System.out.println("File Created:" + created);  // if already same file it created error

        ArrayList<String> stringArrayList = readFileAsList(nameOfNewFile);
        for (String row : stringArrayList) {
            System.out.println("Line:" + row);
        }
        String nameOfWriteFile = "D:\\TechCoding_1\\data\\Practice\\file" + "write-File.txt";
        boolean wroteToFile = writeToFile(nameOfWriteFile, "this file is generated by Suraj Patwa");
        System.out.println(wroteToFile);
        // for append ke lea
        for (int i = 1; i <= 10; i++) {
            String data = i + ""; //String me rahega
            appendToFile(nameOfWriteFile, data);
        }

        // to check append file length
        System.out.println("Appended file length:  " + readFileAsList(nameOfWriteFile).size());
    }

//    public  static void readAndPrintFile(String fileName) {
//        Scanner scanner=null;
//        try{
//          File file =new File(fileName);
//          scanner=new Scanner(file);
//          while(scanner.hasNextLine()){
//              String line=scanner.next();
//              System.out.print(line+" ");
//          }
//
//
//        } catch (FileNotFoundException e) {
//            e.printStackTrace();
//        }
//        finally {
//            if(scanner!=null){
//                scanner.close();
//            }
//        }
//
//    }
    // esse arraylist me chenge kar do


    public static ArrayList<String> readFileAsList(String fileName) {
        Scanner scanner = null;
        ArrayList<String> string = new ArrayList<String>();
        try {
            File file = new File(fileName);
            scanner = new Scanner(file);
            while (scanner.hasNextLine()) {
                String line = scanner.nextLine();
                string.add(line);
            }


        } catch (FileNotFoundException e) {
            e.printStackTrace();
        } finally {
            if (scanner != null) {
                scanner.close();
            }
        }
        return string;

    }

    public static boolean writeToFile(String fileNameWithPath, String content) throws IOException {

        try {
            FileWriter fileWriter = new FileWriter(fileNameWithPath);
            fileWriter.append(content);
            fileWriter.close();
        } catch (Exception e) {

        }
        return true;
    }


    public static boolean appendToFile(String fileName, String content) {
        try {
            FileWriter fileWriter = new FileWriter(fileName, true);
            fileWriter.append("\n");
            fileWriter.append(content);
            fileWriter.close();
        } catch (Exception e) {
            return false;
        }
        return true;
    }

}
